### PR TITLE
hooks concept

### PR DESCRIPTION
**Pull request by jkroso**
I'm just thinking about how hooks should be implemented. Looking at mocha they treat hooks like tests more or less which is a nice concept but I think they might loose some flexibility because of it. They only allow "beforeAll/afterAll" "beforeEach/afterEach" within each suite. I think it would be nice to be able to add hooks to individual tests if you want. The approach I've taken here, which is just to emit a "before" and "after" event on the actual test instances, does put a bit of a burden on the interfaces though (hydro-bdd, hydro-tdd, etc..). Thoughts?

### CODE REVIEW

**Comment by vesln** [comment]
I think the idea is pretty cool, given we've got the concept of `tags`, not very well document and highly used atm, but extremely powerful, proven by `rspec`. 

However, supporting before/after and beforeEach/afterEach on suite level will be required since this is what most people are used to and more or less all modern test suites are leveraging them.

**Comment by jkroso** [comment]
> supporting before/after and beforeEach/afterEach on suite level will be required 

thats what I meant by putting a burden on the interfaces since they would need to track some state in order to offer those concepts. They would have to be more than proxies. I'm not against supporting those hooks within hydro I just think it makes slightly more sense for them to be a feature of the interfaces.

> I think the idea is pretty cool, given we've got the concept of tags

the idea of hooks as tests?

**Comment by vesln** [comment]
Yeah, I had this discussion with @logicalparadox, we were brainstorming what would be better, to basically put the hooks into a plugin, make the interfaces care about them or what have you. My first idea was to implement the hooks as `hydro-hooks`, basically a plugin. However, we ended up agreeing that hooks belong in core more or less, so we keep the interfaces just carrying about how things will look to the end user but not how they work. I think most of the interfaces need pretty much the same functionality or can provide sugar on top of events and hooks that hydro will be responsible for.

I thought the idea of hooks for individual tests is pretty awesome.

I'm also tempted to keep going forward without the hooks. To me this results to _better_ tests, since you generalize and encapsulate the needed functionality into reusable plugins. Some examples extracted out of client apps: clean-dir, ghostd, http-server etc... I've worked on many apps where the test setup was the most complicated part of the test and it was nearly impossible to follow. Also it can lead to a great amount of extra debugging since if something in the before hook changes you'll get say 10 failing tests rather than just one. 

With that said though, I'm having conversations with teams that are looking forward to using hydro, and the lack of hooks seems to be the deal breaker at this point. They can't just adopt this new way of thinking and spend weeks to migrate their test cases and extract plugins, but we do need them to start using it so we can get "real world feedback". 

Not sure if this actually answers any question haha but it's just my take on the whole hook craziness.

**Comment by jkroso** [comment]
perhaps we could make interfaces be the objects that receive the proxy calls rather than hydro itself. So `attachProxies` would be:

``` js
Hydro.prototype.attachProxies = function() {
  var target = this.global();
  var self = this;

  util.eachKey(this.get('proxies'), function(from, to) {
    target[from] = function() {
      return self.interface[to].apply(self.interface, arguments);
    };
  });
};
```

And hydro-bdd would be:

``` js
function(hydro){
  hydro.interface = require('interface')
  hydro.set('proxies', 'when', 'addSuite')
  hydro.set('proxies', 'it', 'addTest')
  hydro.set('proxies', 'before', 'beforeNextTest')
}
```

**Comment by vesln** [comment]
That's a very good idea in many levels. Right now, nothing is stopping you to proxy a private method which is silly. We can start with having `interface` in hydro so nothing needs to require it and if something really needs to overwrite any of the interface methods or even add custom, it should be pretty straight forward. I like it!

**Comment by vesln** [comment]
The `Interface` implementation is done. Next `before`, `after`, `afterAll` and `beforeAll`

**Comment by vesln** [comment]
Which I want to note that is different than what most runners have. before each is more common and more often used than before all so it makes sense to be shorter and easier to write IMHO. As it is in `rspec`

**Comment by jkroso** [comment]
Ok so I've got hooks working now. I implemented them as just event listeners on tests/suites. This was really easy to do but it might be better if they were implemented as a type of test. That way you would have access to features like timeouts, and they would be a properly reified concept which is nice... but I think what I have written is plenty useful. 

@vesln the tests aren't running under component and it seems to be because two hydro files are being loaded onto the page. One is older and ends up overwriting the one I'm trying to test. I think it might be some karma trick that autoloads it. Do you know anything about it?

**Comment by vesln** [comment]
That's fucking awesome! I'll take a look now.

Regarding karma - yeah, most probably my bad, I'll investigate

**Comment by jkroso** [comment]
Oh I ended up fixing that problem with 4c51245. Well the bug at least I'm still a bit confused about how karma works but I must of been wrong about the second file overwriting the first.

**Comment by vesln** [comment]
Btw evts 0.1.0 introduced some major changes in terms of error handling. We gotta make sure that this doesn't break most of the plugins which was the case last time when I updated (I know I'm the author of evts and this sounds weird)

**Comment by jkroso** [comment]
i've run this branch in a suite with:
- hydro-bdd
- hydro-chai
- hydro-html
- hydro-dot

**Comment by vesln** [comment]
@jkroso please review the changes I did and feel free to merge it in if it's fine. I did nothing interesting except making the coding style consistent and providing IE8 fixes. I know that supporting older browsers is super annoying but it's a requirement that I'm forced to have due to the project I'm working on (think google analytics that must work pretty much everywhere).

**Comment by jkroso** [comment]
is `test-sauce` working for you now? I'm getting this error:

the environment you requested was unavailable. Tunnel identifier provided: '1390737080866', didn't match any running tunnel for your account Please remove or specify a different tunnel-identifier. For more info, please check http://saucelabs.com/docs/connect#tunnel-identifier

**Comment by vesln** [comment]
I'm getting the same thing for Chai.js too. Works on Travis though. I'll investigate, and also try #19

**Comment by vesln** [comment]
[This](https://github.com/hydrojs/hydro/commit/26b19cb070b493c2df00c4c45f3019ef9be97cae) fixed it

**Comment by jkroso** [comment]
Yus! finally it runs cleanly on sauce for me

**Pull request merged**
